'''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DO NOT EDIT THIS FILE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''

import io
from unittest import mock, TestCase

from stocks import stock_purchases


class TestStockPurchases(TestCase):

    @mock.patch('builtins.input', side_effect=['Ash', '5000', 'Apple'])
    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_stock_purchases(self, mock_stdout, mock_input):
        stock_purchases()

        # Since we are patching the input() function, those printouts don't appear
        self.assertEqual(
            "Ash has $5000 to invest and can buy 50 shares of Apple at the current price of $100.\n",
            mock_stdout.getvalue()
        )